[mocks] Fix confusing error message.
When a class method was mocked and it was called an extra time with the wrong arguments, the error being raised was:

"NoMethodError: undefined method `bar' for Object:Class"

...which was very confusing.

---
This commit was imported from https://github.com/rspec/rspec-mocks/commit/b03c2fb471831281ede33920f489ff1ea24a47de.