[mocks] Fix confusing error message.
When a class method was mocked and it was called an extra time with the wrong arguments, the error being raised was:

"NoMethodError: undefined method `bar' for Object:Class"

...which was very confusing.

---
This commit was imported from https://github.com/rspec/rspec-mocks/commit/767acd0534d03a94e9efa76b5e0d5d479a564e10.